### ISSUE TITLE
improve: localize in English

### ISSUE THREAD

**Issue by Krystino** [nolebase/nolebase#19]
I'm quite interested in this project, and I want to translate the English documentation. Is it necessary?

**Comment by nekomeowww** [comment]
Welcome, contributor!

For sure!

But what do you mean by "translating the English documentation"? Translating [README.md](https://github.com/nolebase/nolebase/blob/main/README.md) is indeed a head job for us in the near future, but I guess you are not saying you want to translate the entire knowledge base into English, that would be a huge business, am I understanding it correctly?

**Comment by olivla** [comment]
Sorry for my misleading enunciation~ I mean translate the translating [README.md](https://github.com/nolebase/nolebase/blob/main/README.md).hhh

**Comment by nekomeowww** [comment]
Sure. Take your steps.

**Comment by nekomeowww** [comment]
Do you still want to write the documentations?

**Comment by ukea** [comment]
yeah!
