### ISSUE TITLE
bug: 部署时报错：Input buffer has corrupt header: glib: XML parse error: EntityRef: expecting ';'

### ISSUE THREAD

**Issue by ChristineCharlotte** [nolebase/nolebase#26]
I feel terribly sorry to bother you. 
I met an error when delpoy my base, but do not know how to fix it. 
It may be related to `sharp`. Can you help me? 
Great Appreciation!

```
[Error: Input buffer has corrupt header: glib: XML parse error: Error domain 1 code 23 on line 35 column 157 of data: EntityRef: expecting ';']
```
![image](https://github.com/nolebase/nolebase/assets/92929085/ad61c709-c9d7-4bf9-b410-9976c0b32dcb)

Solution I found attached:
<https://stackoverflow.com/questions/23422316/xml-validation-error-entityref-expecting>
![image](https://github.com/nolebase/nolebase/assets/92929085/b32a3c18-7cf6-4483-8bbb-89d7edbd089a)

<https://github.com/lovell/sharp/issues/2420>
![image](https://github.com/nolebase/nolebase/assets/92929085/be107fc2-ade2-4f13-beee-b4e8ded19b61)

**Comment by nekomeowww** [comment]
> I feel terribly sorry to bother you.
> It may be related to sharp. Can you help me?
> Great Appreciation!

Yes, sure! Feel free to ask.

This is quite interesting. Let me open up a Windows-based pipeline to test this out.

**Comment by nekomeowww** [comment]
Sorry but I cannot reproduce this problem on my Windows machine with Nolebase, but I will try to pull your knowledge base to local directory and try again to create a triage for you for further investigation.

Anyway, I've written a complete new guidelines for Windows users to setup their projects on this commit [f89b5e4](https://github.com/nolebase/nolebase/commit/f89b5e473482c4618bd67d2d45e336640a6466ed), maybe you can double check on this to make sure nothing get wrong before going any deeper.

**Comment by nekomeowww** [comment]
<img width="900" alt="image" src="https://github.com/nolebase/nolebase/assets/11081491/07194276-874b-46ba-8dee-3959292c533e">

I tried with your repository and the building process is fine.

What is your Node.js, pnpm.js, Python versions? Perhaps I can create an environment exactly the same for triage.

**Comment by nekomeowww** [comment]
Closed due to stale.

**Comment by nekomeowww** [comment]
Related:

<img width="1027" alt="image" src="https://github.com/nolebase/nolebase/assets/73946940/8c18fc7d-175a-444a-8a37-0e8dfa91cc30">

_Originally posted by @jiechen257 in https://github.com/nolebase/nolebase/issues/36#issuecomment-1978338254_

**Comment by luoling8192** [comment]
It cause by NodeJS LTS version.

**Solution: Upgrade NodeJS version to 21 or later**

[This Issue](https://github.com/nodejs/node/issues/48673) might help.
