### ISSUE TITLE
bug: 开发服务器下生成了错误的链接

### ISSUE THREAD

**Issue by Nisekoi5** [nolebase/nolebase#28]
生成了绝对路径的相对路径，导航过去会404
![image](https://github.com/nolebase/nolebase/assets/49276902/060b78d4-8325-4a6d-bc74-257d8de83817)
复现的仓库
https://github.com/Nisekoi5/nolebase
下面由actioin构建后的页面生成的链接正常 
https://velvety-gumption-30da13.netlify.app/%E7%AC%94%E8%AE%B0/%F0%9F%93%9F%20%E7%BB%88%E7%AB%AF/Linux%20%E5%91%BD%E4%BB%A4%E7%B4%A2%E5%BC%95.html

另外还有些小问题, 
同样在开发模式下，首页会有几个不合群的元素，在构建后消失
![image](https://github.com/nolebase/nolebase/assets/49276902/f551d097-c2ec-4264-bc50-4f496d63425a)

**Comment by nekomeowww** [comment]
应该是 [Nolebase Integrations](https://github.com/nolebase/integrations) 下面的 [markdown-it-bi-directional-links](https://nolebase-integrations.ayaka.io/pages/zh-CN/integrations/markdown-it-bi-directional-links/) 和 [vitepress-plugin-git-changelog](https://github.com/nolebase/integrations/tree/main/packages/vitepress-plugin-git-changelog) 产出的路径和历史记录的渲染有点问题。

> 同样在开发模式下，首页会有几个不合群的元素，在构建后消失

我看看，我还确实没有观察过 dev server 的时候的问题，应该是 `GitChangelogMarkdownSection` 这个 Vite 里面的插件导致的。

**Comment by nekomeowww** [comment]
你也是在 Windows 环境下开的 dev server 吗？我怀疑都是 Windows 的路径系统不兼容导致的 😂。

好久没有在 Windows 上处理过路径了，看来有些地方在跨平台这个方面考虑的不是很周全，造成了这些问题，我处理一下。

**Comment by Lercel** [comment]
是的，我也是在Windows环境下开的 dev server。Many thanks~~

**Comment by Nisekoi5** [comment]
> 你也是在 Windows 环境下开的 dev server 吗？我怀疑都是 Windows 的路径系统不兼容导致的 😂。
> 
> 好久没有在 Windows 上处理过路径了，看来有些地方在跨平台这个方面考虑的不是很周全，造成了这些问题，我处理一下。

嗯，是在windows上运行的

**Comment by nekomeowww** [comment]
应该已经修好了呢。可以拉一下最新的 Nolebase 到本地看看。

@Lercel 可以根据 https://github.com/nolebase/nolebase/pull/29/files 的修改更新一下你的 Vision 的依赖版本和 vite.config.ts 的配置呢，应该就能解决 Windows 上的路径不兼容的问题了。

谢谢汇报这样的错误，真的很感谢！

**Comment by Nisekoi5** [comment]
> 应该已经修好了呢。可以拉一下最新的 Nolebase 到本地看看。
> 
> @Lercel 可以根据 https://github.com/nolebase/nolebase/pull/29/files 的修改更新一下你的 Vision 的依赖版本和 vite.config.ts 的配置呢，应该就能解决 Windows 上的路径不兼容的问题了。
> 
> 谢谢汇报这样的错误，真的很感谢！

首页的异常元素没有了。但是链接还是一样的会404，试过在我fork的仓库同步提交和直接clone一份新的主仓库的代码都一样。

**Comment by Nisekoi5** [comment]
![image](https://github.com/nolebase/nolebase/assets/49276902/e4238aff-8df8-4889-9eea-57d41efc3fbc)

**Comment by nekomeowww** [comment]
看起来是之前那一份的 markdown-it-bi-directional-links 的发布有点问题，我重新发了一版，测试了一下发现都正常了。

<img width="1425" alt="image" src="https://github.com/nolebase/nolebase/assets/11081491/44088b7d-8cea-478e-a365-112b8a0891de">

cc @Lercel

**Comment by Nisekoi5** [comment]
现在工作正常👍
