### ISSUE TITLE
tip: unset git protectNTFS can resolve a char error

### ISSUE THREAD

**Issue by morninghut** [nolebase/nolebase#35]
clone项目到本地时遇到了报错：

```bash
PS E:\desktop> git clone https://github.com/nolebase/nolebase
Cloning into 'nolebase'...
remote: Enumerating objects: 6762, done.
remote: Counting objects: 100% (877/877), done.
remote: Compressing objects: 100% (288/288), done.
remote: Total 6762 (delta 632), reused 809 (delta 579), pack-reused 5885Receiving objects: 100% (6762/6762), 140.42 MiB | 19.00 MiB/s
Receiving objects: 100% (6762/6762), 141.24 MiB | 14.55 MiB/s, done.
Resolving deltas: 100% (4075/4075), done.
error: invalid path '编目 Catalog/文章/Python, Go, and TypeScript: My Insights on Crafting Command Line Interfaces.md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

PS E:\desktop> cd .\nolebase\
PS E:\desktop\nolebase> git restore --source=HEAD :/
error: invalid path '编目 Catalog/文章/Python, Go, and TypeScript: My Insights on Crafting Command Line Interfaces.md'
```

Google了下，在[这里](https://confluence.atlassian.com/bitbucketserverkb/error-invalid-path-during-git-clone-to-windows-client-1085186345.html)看到了问题原因和解决方法：

```bash
git config --global core.protectNTFS false
```

原因：
> Windows reserves certain file names so trying to create a file that uses a reserved base name should fail.
>
> Please refer to the [Naming a file](https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file) Windows documentation:
> 
>     Do not use the following reserved names for the name of a file:
> 
>     CON, PRN, AUX, NUL, COM1, COM2, COM3, COM4, COM5, COM6, COM7, COM8, COM9, LPT1, LPT2, LPT3, LPT4, LPT5, LPT6, LPT7, LPT8, and LPT9. Also avoid these names followed immediately by an extension; for example, NUL.txt is not recommended

设置过`git config --global core.protectNTFS false`后问题解决了。似乎是仓库里某个文件名的字符引起的错误？

附带极长的 git status [输出](https://gist.github.com/morninghut/5442f4a7e5862c6c4d60b295fc93948d)

**Comment by nekomeowww** [comment]
@morninghut 好的了解！谢谢你的反馈！我现在去更新一下非法文件名

我在 Windows CI 中添加一下检查试试看未来能不能避免这样的问题。

**Comment by morninghut** [comment]
@nekomeowww 感觉可能是git for windows的bug，或许在本地部署里加一下对Windows用户的说明比较简单？[StackOverflow](https://stackoverflow.com/questions/63727594/github-git-checkout-returns-error-invalid-path-on-windows)
~~反正只是一行命令的事~~

**Comment by nekomeowww** [comment]
我发现这个 CI 还挺难的，隔壁 [nolebase/integrations](https://github.com/nolebase/integrations) 的 Windows CI 就没有这么多问题，我可能得再花时间看看如何 debug 和复现这个问题。（比如加一个 ssh 到 GitHub Actions 的能力，今天晚点我会看看）

至于 `git config --global core.protectNTFS false`，不知道你愿不愿意帮忙贡献文档呢？如果愿意的话你可以帮忙撰写相关的说明和注释，写到 `笔记/index.md` 和 `README.md` 就好了。

如果你很忙碌的话，那我晚点自己修改一下即可。

**Comment by morninghut** [comment]
PR可以的！今晚应该有时间加进去
