### ISSUE TITLE
在`nodejs v20` 中无法正常使用

### ISSUE THREAD

**Issue by Nisekoi5** [nolebase/nolebase#40]
OS Version: Windows11
Node.js Version: v20.11.0 (LTS版本)

因上游库的原因，包含emoji的目录无法获取，所以`update.ts`无法生成元数据导致一系列问题 。
https://github.com/mrmlnc/fast-glob/issues/436

换成v18后正常工作

**Comment by nekomeowww** [comment]
能直接加一行文档说一下吗？

**Comment by luoling8192** [comment]
在 Windows 下面 NodeJS LTS 版本有处理emoji的bug，解决方法是切换到 NodeJS 21

**Comment by Nisekoi5** [comment]
当然可以啊，上次手机看到邮件给已读忘了回复了。这下才想起来

**Comment by nekomeowww** [comment]
没动静好久了。

不过，[Node v22 已经出了](Node.js — Node.js 22 is now available!
https://nodejs.org/en/blog/announcements/v22-release-announce)，建议大家升级到 Node v22
