### ISSUE TITLE
Overload 1 of 3, '(plugin: PluginSimple): MarkdownIt', gave the following error.

### ISSUE THREAD

**Issue by garygan89** [nolebase/nolebase#51]
Using node `v22.2.0`

All MarkdownIt plugin is not usable, fresh clone from `master` branch.

![image](https://github.com/nolebase/nolebase/assets/2649703/084c6e7d-33d3-4979-bbf6-7f0313a37439)

**Comment by nekomeowww** [comment]
> Using node `v22.2.0`
> 
> All MarkdownIt plugin is not usable, fresh clone from `master` branch.
> 
> ![image](https://private-user-images.githubusercontent.com/2649703/337872579-084c6e7d-33d3-4979-bbf6-7f0313a37439.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5NDI5MjMsIm5iZiI6MTcxNzk0MjYyMywicGF0aCI6Ii8yNjQ5NzAzLzMzNzg3MjU3OS0wODRjNmU3ZC0zM2QzLTQ5NzktYmJmNi03ZjAzMTNhMzc0MzkucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MDlUMTQxNzAzWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MDI0NDlmNzgzODg1YWQ0NDkxMmE3MjE4MTM1OTUyMDFhYmQ3OTJjNTcyNDhkNDIyMjVjNjRiOGQzNDc0ZmM0YSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.UjfplbO1PDgr8XP36Bp3xvEd0bXBBUv1SaRGO6-7Lnk)

I tried to fix this issue last week during https://github.com/nolebase/integrations/pull/228 , however I failed to patch and fix this type mismatch issue.

Such issue was due to the breaking change introduced by both upstream markdown-it and VitePress and the incompatibilities against markdown-it@v14. You can add a `as any` as temporary fix.

**Comment by nekomeowww** [comment]
Hello, this should be fixed after https://github.com/nolebase/integrations/pull/240 .
