### ISSUE TITLE
部分页面无法正常显示

### ISSUE THREAD

**Issue by walterfang1209** [nolebase/nolebase#60]
我的笔记目录下有一篇名为`P9313 [EGOI2021] Shopping Fever  购物热 题解`的文章和一些其他的文章，均为 `md` 格式。在我通过 `Vercel` 进行部署后，其他文章内容均能正常显示，但是这篇文章点击时提示 `404 PAGE NOT FOUND`，具体如下图所示：
![GIF 2024-7-26 17-52-12](https://github.com/user-attachments/assets/8512de41-dbc4-4160-bdec-178da026560e)
![无标题](https://github.com/user-attachments/assets/fb499232-d61b-4455-9f4c-347d5398187d)
请问该如何解决这个问题？
我的项目的 `Github` 仓库地址为 [https://github.com/walterfang1209/nolebase-template](https://github.com/walterfang1209/nolebase-template)。
非常感谢。

**Comment by nekomeowww** [comment]
你好！谢谢你来到 Nolebase 社区。

我在本地的 Nolebase 中尝试了你的文件，是能够正确渲染、展示，和导航的。

请问：

- 在 `pnpm docs:build` 本地构建之后能通过 `pnpm docs:preview` 的本地预览服务器交互吗？
- 请问部署之后点击侧边栏的链接之后，顶部地址栏的地址是什么样的？

**Comment by walterfang1209** [comment]
> 你好！谢谢你来到 Nolebase 社区。
> 
> 我在本地的 Nolebase 中尝试了你的文件，是能够正确渲染、展示，和导航的。
> 
> 请问：
> 
> * 在 `pnpm docs:build` 本地构建之后能通过 `pnpm docs:preview` 的本地预览服务器交互吗？
> * 请问部署之后点击侧边栏的链接之后，顶部地址栏的地址是什么样的？

感谢您的回复！事实上，我的仓库 `Fork` 自 [这个仓库](https://github.com/Jackiexiao/nolebase-template)，我将自己的仓库与 `Vercel` 中的项目绑定后直接用 `Vercel` 进行部署，所以我并没有使用 `pnpm`。

**Comment by nekomeowww** [comment]
> 感谢您的回复！事实上，我的仓库 Fork 自 [这个仓库](https://github.com/Jackiexiao/nolebase-template)，我将自己的仓库与 Vercel 中的项目绑定后直接用 Vercel 进行部署，所以我并没有使用 pnpm。

好吧，没事，我找时间帮你 debug 看看吧。最大的可能是使用了路径中不受支持或者无法匹配的字符串导致的，你可以试试看把页面的名字改成简单一些的文本和只用纯英文数字的结构看看是否有效。

**Comment by walterfang1209** [comment]
> 你好！谢谢你来到 Nolebase 社区。
> 
> 我在本地的 Nolebase 中尝试了你的文件，是能够正确渲染、展示，和导航的。
> 
> 请问：
> 
> * 在 `pnpm docs:build` 本地构建之后能通过 `pnpm docs:preview` 的本地预览服务器交互吗？
> * 请问部署之后点击侧边栏的链接之后，顶部地址栏的地址是什么样的？

你好！现在我尝试在本地部署，但是出现了如下报错：
![无标题](https://github.com/user-attachments/assets/5883b1a1-fe85-4309-ae22-a81696b3886c)

**Comment by nekomeowww** [comment]
> 你好！现在我尝试在本地部署，但是出现了如下报错

通常是因为代理没有正确配置导致的。如果你正在使用 Clash for Windows，你可以通过寻找 Clash for Windows 中的 TUN Mode（或者 TUN 模式 或者 增强模式）激活并开启它，然后在命令行中使用

```
curl "https://google.com"
```

来测试是否能够访问到受限的互联网域名来尝试解决问题。

**Comment by walterfang1209** [comment]
> > 你好！现在我尝试在本地部署，但是出现了如下报错
> 
> 通常是因为代理没有正确配置导致的。如果你正在使用 Clash for Windows，你可以通过寻找 Clash for Windows 中的 TUN Mode（或者 TUN 模式 或者 增强模式）激活并开启它，然后在命令行中使用
> 
> ```
> curl "https://google.com"
> ```
> 
> 来测试是否能够访问到受限的互联网域名来尝试解决问题。

但是我没有使用代理

**Comment by nekomeowww** [comment]
> 但是我没有使用代理

那应该是会遇到问题的。

**Comment by walterfang1209** [comment]
> Reference in new

请问该如何解决？谢谢。

**Comment by nekomeowww** [comment]
> 请问该如何解决？谢谢。

恐怕已经超出了 Nolebase 社区的支持范围了。

不过！我帮你找了三个可以参考的 GitHub 仓库，理论上你只需要能够访问到 GitHub 就是可以阅读的：

- Sha1rholder/Clash-against-GFW: 傻瓜式教程——如何使用Clash翻墙 https://github.com/Sha1rholder/Clash-against-GFW
- zhaoweih/Shadowsocks-Tutorial: 🐱给小白的Shadowsocks翻墙教程-Easy-to-follow tutorials for beginners on using Shadowsocks to bypass internet restrictions. https://github.com/zhaoweih/Shadowsocks-Tutorial
- zhaoweih/ChatGPT-in-China: 🤖如何在国内注册和使用ChatGPT-How to register and use ChatGPT in China https://github.com/zhaoweih/ChatGPT-in-China?tab=readme-ov-file

我手头上并没有 Windows，还请拜托你阅读一下上述的资料或者搜索类似的关键字来找到完整的教程。

**Comment by walterfang1209** [comment]
> > 请问该如何解决？谢谢。
> 
> 恐怕已经超出了 Nolebase 社区的支持范围了。
> 
> 不过！我帮你找了三个可以参考的 GitHub 仓库，理论上你只需要能够访问到 GitHub 就是可以阅读的：
> 
> * Sha1rholder/Clash-against-GFW: 傻瓜式教程——如何使用Clash翻墙 https://github.com/Sha1rholder/Clash-against-GFW
> * zhaoweih/Shadowsocks-Tutorial: 🐱给小白的Shadowsocks翻墙教程-Easy-to-follow tutorials for beginners on using Shadowsocks to bypass internet restrictions. https://github.com/zhaoweih/Shadowsocks-Tutorial
> * zhaoweih/ChatGPT-in-China: 🤖如何在国内注册和使用ChatGPT-How to register and use ChatGPT in China https://github.com/zhaoweih/ChatGPT-in-China?tab=readme-ov-file
> 
> 我手头上并没有 Windows，还请拜托你阅读一下上述的资料或者搜索类似的关键字来找到完整的教程。

你好，我使用 `pnpm docs:dev` 指令时看到了报错内容，麻烦您帮我看下，谢谢。这两篇文章（黄字）在 deploy 到网站上后显示都有问题。
![1](https://github.com/user-attachments/assets/4f180c61-6e5f-4a65-901f-f8c127463929)

**Comment by northword** [comment]
路径不要包含 `[]`

**Comment by northword** [comment]
另外严格地，我建议你参照阮一峰老师的 [中文技术文档协作规范](https://github.com/ruanyf/document-style-guide?tab=readme-ov-file) ，文件名仅使用小写字母和连字符。考虑到中文知识库需求，中文在文件名中也可以考虑，此外的一切其他符号、空格都不应在路径中使用，以避免未知问题。

**Comment by nekomeowww** [comment]
如果还有别的疑问请随时提问，也欢迎加入我们的 Discord 服务器讨论 https://discord.gg/XuNFDcDZGj 。
