### ISSUE TITLE
相同目录下可以引用其他类型的资源吗？

### ISSUE THREAD

**Issue by shelken** [nolebase/nolebase#63]
例如我在markdown中引用一个相同目录或者在assets目录下的zip文件或者sh文件或者word文档。这种情况下点击链接最后还是跳到一个html页面。有什么配置或者方式可以在点击时直接触发下载吗？

**Comment by nekomeowww** [comment]
这个没有限制过。

是不是根本没有打包到一起导致的呢？可以试试看配置一下这个 https://github.com/nolebase/nolebase/blob/main/vite.config.ts#L14C5-L14C18

**Comment by shelken** [comment]
我是使用`pnpm run docs:dev`运行的。配置了，似乎没有生效。
![image](https://github.com/user-attachments/assets/5fd68780-cc9c-4947-8c68-91e42c850554)
![image](https://github.com/user-attachments/assets/ded899d0-8b71-406a-8447-283849514b2f)
![image](https://github.com/user-attachments/assets/fc24a18b-2feb-47bf-ae18-20fbdcf68b5d)

**Comment by nekomeowww** [comment]
网站在哪里，我可以帮忙看看。

**Comment by nekomeowww** [comment]
好久没有更新了，如果有需要帮忙 debug 的可以再打开 issue。
