### ISSUE TITLE
vue生成后资源路径错误问题

### ISSUE THREAD

**Issue by Y-ASLant** [nolebase/nolebase#72]
![Clip_2024-10-16_10-28-22](https://github.com/user-attachments/assets/63f75548-8060-42e8-9814-3fe4a4316426)
生成后必须改成./才可正确加载相对路径下的文件，直接导出打开就是白屏

**Comment by LittleSound** [comment]
你可以提供原始代码，和生成后的结果的对比吗。知道具体是怎么样的情况和配置会更有利于进行复现。

**Comment by Y-ASLant** [comment]
> 你可以提供原始代码，和生成后的结果的对比吗。知道具体是怎么样的情况和配置会更有利于进行复现。

就是直接在Windows下git下来，安装完所需要环境后，直接运行pnpm build，然后进入.vitepress/dist/打开index.html就找不到文件，但是在vue中直接运行没有问题，我百度了一下，可能是vue本身的原因

**Comment by LittleSound** [comment]
原来是这样。因为我平时使用的都是 MacOS，所以我想，可能有我没发现的兼容性问题。

**Comment by LittleSound** [comment]
我仔细看了一下，我这边还是无法复现。

但是我注意到一个细节，你说

> 进入.vitepress/dist/打开index.html就找不到文件

实际上，如果你想要正常访问这个构建产物，你需要输入这个命令在你的本地启动一个服务器来挂载这个网站

```shell
pnpm run serve
```
