### ISSUE TITLE
部署失败

### ISSUE THREAD

**Issue by lgf5090** [nolebase/nolebase#74]
部署失败
![image](https://github.com/user-attachments/assets/a5eff91e-de02-4604-8496-b40f701a5f58)

**Comment by nekomeowww** [comment]
最新的提交会造成内存耗尽，这个问题我之前还没有找到可以修复的办法，等我今天更新一下依赖看看。

**Comment by nekomeowww** [comment]
更新了一下依赖发现是 og-image 造成的问题，可以先关掉这个插件试试。
