### ISSUE TITLE
侧边的大纲不显示一级标题

### ISSUE THREAD

**Issue by PXforever** [nolebase/nolebase#75]
我发现侧边的大纲无法显示一级标题，这让文档跳转不是很方便。

**Comment by nekomeowww** [comment]
VitePress 默认排除 h1（因为无论是从语义化规范来说，还是对屏幕阅读器，以及搜索引擎，每一个页面都只应有一个 h1 标签），如果你真的需要，可以根据这个进行配置：https://vitepress.dev/reference/default-theme-config#outline
