### ISSUE TITLE
improve: translate README into English

### ISSUE THREAD

**Issue by indexss** [nolebase/nolebase#77]
I know there is already an issue #19 to translate the README document, but it seems that there has been no progress for several months.

I am curious if the translation work is still in progress or not. If possible, it's OK to assign the translation task to me. I can provide the English translation of the project README. 

btw Nolebase's presentation of the knowledge base is really great. I have already migrated the content which was originally deployed on GitBook. Thanks to the developers!

**Comment by nekomeowww** [comment]
Hi, it's nice to see you here. And welcome to the Nolebase community.

Yes, another issue has been staled for long a while. I've already assigned you.

And for translation, it's fine if you would like to translate it progressively (means to translate the document partially and continuously). 
And... Take you time!

**Comment by indexss** [comment]
Hi. I have completed the English translation of the README and submitted a PR. However, during the "构建预览" workflow, an error occurred at the "Set up job" stage with the following message:

```
Error: This request has been automatically failed because it uses a deprecated version of actions/upload-artifact: v2. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
```

I am not that familiar with CI/CD, but based on the error message, it seems that the `actions/upload-artifact: v2` tag in `.github/workflows/preview-docs-build.yaml` has been deprecated, and the website recommends using v4. The following is the content mentioned on the website in the error message:
> In order to prevent issues for customers using GitHub Connect, the tags for v1 through v2 will not be removed from the actions/upload-artifact and actions/download-artifact project repositories. However, attempting to use a version of the actions after the announced deprecation date will result in a workflow failure.

Since I am not well-versed in this area, I would appreciate some guidance. Thanks!

**Comment by nekomeowww** [comment]
No worries, thanks for telling me and notifying me that, already fixed.
