### ISSUE TITLE
WireGuard 文档的小问题

### ISSUE THREAD

**Issue by blurh** [nolebase/nolebase#8]
> 重新生成一对客户端密匙
>
> privatekey1 为客户端私钥，publickey1 为客户端公钥
>
> wg genkey | sudo tee cprivatekey1 | wg pubkey > sudo cpublickey1

输出重定向这里有点问题, 多了个 sudo, 应该去掉

```bash
wg genkey | sudo tee cprivatekey1 | wg pubkey > cpublickey1
```

**Comment by nekomeowww** [comment]
谢谢勘误！

我备两种命令吧，一种 `sudo` 的一种不 `sudo` 的

**Comment by nekomeowww** [comment]
已经好了：https://nolebase.ayaka.io/to/bc31ad294a

**Comment by blurh** [comment]
sorry 是我没说清楚是哪个文档, 是 [WireGuard VPN 多用户管理](https://github.com/nolebase/nolebase/blob/58bf2cc22a7f6a192caeecce844c78a707a2c10e/%E7%AC%94%E8%AE%B0/%E2%98%81%EF%B8%8F%20%E5%90%8E%E7%AB%AF%E5%BC%80%E5%8F%91/%F0%9F%95%B8%20%E7%BD%91%E7%BB%9C/WireGuard%20VPN/WireGuard%20%E5%A4%9A%E7%94%A8%E6%88%B7%E7%AE%A1%E7%90%86.md?plain=1#L27) 这个文档

**Comment by nekomeowww** [comment]
🤔️ 原来还有我遗漏的，我都过一遍好了，谢谢再次说明。

**Comment by nekomeowww** [comment]
@blurh  好了： https://nolebase.ayaka.io/to/50c5b38cc3
